name: Build, Test, and Clean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build project
        run: make

        - name: Clean project
        run: make fclean
